### ISSUE TITLE
Неочевидный data flow

### ISSUE THREAD

**Issue by prodderman** [grzdrz/FSD_Task4#10]
В презентере не понятны во эти методы:
![image](https://user-images.githubusercontent.com/24736776/101498843-277cb680-399f-11eb-851c-350620882faf.png)
Тут максимально не понятно что происходит. Очень не очевидно через мутации аргументов как то получать/передавать данные. Никогда так не делай, пожалей людей которые будут читать твой код

**Comment by prodderman** [comment]
Картина в целом не поменялась: в updateFilledStrips, например, после вызова this.model.onExtractViewData.invoke(); ты надеешься что кто то снаружи замутирует this.model.viewData. тебе нужно продумать более очевидный контракт передачи данных из вьюхи в модель

**Comment by prodderman** [comment]
И почему модель вообще запрашивает данные из вьюхи? Вьюха должна просто отображать данные модели

**Comment by grzdrz** [comment]
переделал(забыл пронумеровать ишьюсы), сделал закос под реакт-редакс датафлоу

**Comment by prodderman** [comment]
Уже лучше, но у тебя все еще есть неочевидный флоу.
После изменения модели во вьюхе мутируется modelData без каких либо оповещений об изменениях. Я бы понял такое, если бы у тебя modelData был Proxy.

В целом получается все еще не очевидно. Теперь вьюха надеется, что кто-то сверху замутирует modelData.
А реагирует она на эти изменения путем подписки самой на себя во ViewManager:
![image](https://user-images.githubusercontent.com/24736776/102082871-47035b80-3e45-11eb-9d8f-f41bda057f2e.png)

+ В Handle.ts при перетаскивании ползунка ты мутируешь все modelData:
![image](https://user-images.githubusercontent.com/24736776/102083926-eaa13b80-3e46-11eb-9ab0-3034cd429a79.png)

Тебе нужно или во вьюхе брать стейт модели напрямую (активная вьюха), или при изменении модели вызывать обновление вьюхи, прокидывая в этот метод весь стейт модели (пассивная вьюха). При этом не нужно дублировать стейт модели во вьюхе что при первом варианте, что при втором.

**Comment by grzdrz** [comment]
можно ли использовать вариант с активной вьюхой? просто прокидывание модел-даты через аргументы во все функции где она нужна выглядит как то жестковато

**Comment by prodderman** [comment]
Почему жесковато? по памяти или по скорости? В твоем случае ты создашь один объект с данными и ссылку на него прокинешь во все вьюхи. У тебя как раз для этого уже есть механизм: 
![image](https://user-images.githubusercontent.com/24736776/102181594-749be380-3edd-11eb-95d9-0f107a1fb31d.png)
только в update будешь прокидывать весь стейт

**Comment by grzdrz** [comment]
жестковато в плане того что модел-дата используется еще и в обработчиках нативных ивентов, и получается ее как то туда пропихнуть еще нужно

**Comment by prodderman** [comment]
1. про нативный эвент не совсем понял. Что тебе мешает на ресайз также эмитить событие, а в презентере прокидывать данные из модели

2. вся коммуникация между вьюхой и моделью происходит в презентере, включая перевод данных из вьюхи в данные модели

**Comment by grzdrz** [comment]
сделал

**Comment by prodderman** [comment]
Да сейчас намного очевиднее получилось. Но в идеале нужно чтобы модель определяла контракт данных, которые она принимает, а не зависела от данных вьюхи. Презентер в этом случае должен принимать данные из вьюхи и конвернтить в данные модели. Закрываю ишью
